### PR TITLE
Update state visualizer sample to latest webpack.

### PR DESCRIPTION
**Pull request by cgranade**
This PR updates the state visualizer sample to use the latest version of webpack.

### CODE REVIEW

**Review by msoeken — APPROVED** [review]

**Comment by cgranade** [comment]
It looks like this PR is blocked on the build agent running out of disk space; @bettinaheim and @anpaz for awareness.

**Review by anpaz — APPROVED** [review]
lgtm

**Review by anjbur — APPROVED** [review]
I ran Component Governance against this branch and confirmed that it resolved the alert! Looks good to me

**Comment by ScottCarda-MS** [comment]
@cgranade Is there any update on this PR? Can it be merged in now that it has approval, or is there more work to be done for this?

**Comment by cgranade** [comment]
> @cgranade Is there any update on this PR? Can it be merged in now that it has approval, or is there more work to be done for this?

As discussed offline, this PR still needs to be bumped to the most recent available beta package; I think 0.15.2104136839-beta should hopefully do it.

**Pull request merged**
