### PR TITLE
Reduce warnings and improve style guide adherance.

### PR DESCRIPTION
**Pull request by cgranade**
This PR reduces the number of warnings by updating to avoid deprecated functions and operations. This PR also makes improvements to readability by using recent improvements in the libraries and by improving style guide adherance.

### CODE REVIEW

**Comment by cgranade** [comment]
It looks like whatever transient issue was affecting builds has since been resolved, such that this should now be reviewable.

**Review by msoeken — APPROVED** [review]
Thanks for all that work @cgranade. Nice to also see the evolution of the libraries in these changes.

**Pull request merged**
