### PR TITLE
Wrong file reference (?) in F# sample

### PR DESCRIPTION
**Pull request by geduardo**
Also, I cannot find the solution file for Fsharp in the sample.

### CODE REVIEW

**Comment by tcNickolas** [comment]
And good point about missing `.sln` file - I missed this comment in the first read, sorry, and it is needed for VS to figure out the project dependency. Do you want to add one as part of this PR? It should probably be in the `/samples/interoperability/fsharp` folder.

**Comment by geduardo** [comment]
I'm not very familiar with Visual Studio so didn't know how to create it, but I can do some research and try. I'll ping you if I need help.

**Comment by tcNickolas** [comment]
I can do it in about 2 minutes, so let's save you some research effort :-) Let's merge this PR and I'll open another one.

**Comment by geduardo** [comment]
Thanks! I'll learn for the next time!

**Pull request merged**
