### PR TITLE
Grammar indentation fixes

### PR DESCRIPTION
**Pull request by russell-taylor**
Fixes comments and an error message and adjusts comment indentation to be consistent on the SimpleAlgorithms.qs file.

### CODE REVIEW

**Comment by anpaz-msft** [comment]
Hi @russell-taylor,  are you still interested in contributing these changes?
If so, please merge and update the PR, otherwise we'll have to close it.

**Comment by russell-taylor** [comment]
I'll be glad to if they will be merged.  After 6 months without a peep I lost hope that they would be.  Lemme know if there is interest in merging the pull request if I change them.

**Comment by russell-taylor** [comment]
Awesome!

**Comment by anpaz-msft** [comment]
Thanks @russell-taylor; changes are now committed into master!

**Pull request merged**
