### PR TITLE
2022.05 Release. Updated the QDK version to 0.24.210930.

### PR DESCRIPTION
**Pull request by kuzminrobin**

### CODE REVIEW

**Comment by kuzminrobin** [comment]
Based on [this](https://github.com/microsoft/Quantum/pull/574#issuecomment-952354663) I tried to test the link
https://mybinder.org/v2/gh/microsoft/Quantum/release-branch/v0.24.210930-mybinder-test
I got:
`Could not resolve ref for gh:microsoft/Quantum/release-branch/v0.24.210930-mybinder-test. Double check your URL. GitHub recently changed default branches from "master" to "main"`.

Will try again after the CI build succeeds.

**Comment by tcNickolas** [comment]
I think there genuinely is no branch called "release-branch/v0.24.210930-mybinder-test" in this repo.
The link https://mybinder.org/v2/gh/microsoft/Quantum/release-branch/v0.24.210930 (with the URL matching the name of the branch used in this PR) does get past resolving the branch.
I suspect that that branch was created separately for testing that PR, though I cannot say what the difference was between it and the PR branch.

**Comment by kuzminrobin** [comment]
I'm testing the link  https://mybinder.org/v2/gh/microsoft/Quantum/release-branch/v0.24.210930

**Comment by kuzminrobin** [comment]
Based on the instructions [here](https://github.com/microsoft/Quantum/pull/574#issuecomment-952354663) I opened the samples/diagnostics/visualization/"visualizing quantum programs" sample and made sure it runs (no kernel death issue).

Please review.

**Comment by kuzminrobin** [comment]
Please provide comments or approve.

**Review by IsraelMiles — APPROVED** [review]

**Pull request merged**
